name: infinite_carousel
description: A Flutter package for implementing an infinite carousel widget.
version: 0.1.0
homepage: https://github.com/Luigi-jp/flutter-infinite-carousel

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true